### ISSUE TITLE
请问有没有可以一键下载所有照片视频的函数呢？

### ISSUE THREAD

**Issue by slin60** [hexin-lin-1024/yikeWebClientPython#1]
如题，下载的照片最好包含exif信息。

**Comment by hexin-lin-1024** [comment]
> 如题，下载的照片最好包含exif信息。

事实上一刻相册并不会删改exif信息，但是对于原本就没有exif信息的图片要获取时间后写入，因为文件创建时间会被覆盖。
没有这个函数，您可以获取全部视频的链接后下载。

`v = getvideos();
link = [i.getdl() for i in v]`

此案例中，link是一个包含全部视频链接字符串的列表。
